### PR TITLE
add preview panel for comments

### PR DESCRIPTION
**Pull request by DouweKoopmans**

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
I expected this to continue on #391, are there potential merge conflicts I should take in to consideration when merging this?

**Comment by DouweKoopmans** [comment]
there are no merge conflicts between this branch and #391, however in order for markdown to be displayed in previews the markdown parser needs to be applied to the previewed content first. 

I'd suggest we first merge this branch, I will then be able to apply any fixes to #391 so markdown is also used in previews, after this #391 should be ready to be merged.

**Comment by Fastjur** [comment]
I suggest merging this into your local #391. In case of conflicts you can fix these locally and push to this remote branch again, which then can be merged into master effortlessly (and makes the WIP #391 redundant)

**Comment by JWGmeligMeyling** [comment]
Please rebase on the Markdown branch, we will use PR #400

**Pull request closed without merging**
