### PR TITLE
Emojis, fixes #322

### LINKED ISSUE #322: Emoji support for messages
> # Title: Emoji reactions to commit
> # Narrative:
> As a student
> I want to be able to react to commits with emojis
> So that I can quickly express my feelings towards the commit.
> # Acceptance Criteria:
> ## Scenario 1: React to a failed build
> Given a failed build commit
> And I'm unhappy that this has happened
> When I click on an emoji button
> Then I want to be able to pick an emoji (such as the poop emoji)
> And attach that to the commit.

*As requested on Slack*

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Replaces #392

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
@Fastjur Can you rebase your `emojis` branch on the current `MarkDownRendering` branch? It seems you have duplicated @DouweKoopmans commits. They need to be removed from this PR.

**Comment by Fastjur** [comment]
Hmm this is weird, I checked out from that branch, that is why the commits are in this one most likely. However when rebasing `emojis` onto `MarkdownRendering` I lose all the changes from `emojis`. Git plz...

**Comment by Fastjur** [comment]
Hmm this is so weird...

**Comment by JWGmeligMeyling** [comment]
Rebased on `emojis`. We still need to do some tricks client side so the emojis display everywhere. Perhaps we should also include some kind of list of possible emojis, or link to a page that has them listed?

**Comment by Fastjur** [comment]
> We still need to do some tricks client side so the emojis display everywhere.

This has been added in the last commits. The emojis are now universal (img tags).

**Comment by JWGmeligMeyling** [comment]
Will checkout later today :smile: Thanks!

**Comment by Fastjur** [comment]
Added the emoji hinting when typing. **Ready to merge**

**Comment by TimvdLippe** [comment]
This PR introduces a new dependency `twemoji` which accounts for 0.5GB of the total 1GB of the whole repository. Was there any comparison between different implementations to support emojis? Seems like a very big hit for such a small change :O

**Pull request merged**
