### PR TITLE
New erd, fixes #161 fixes #248 fixes #249 fixes #250 fixes #251 fixes #256

### LINKED ISSUE #161: Students can create same group twice

### LINKED ISSUE #248: Abstract Pull Request/Issue, impl issue number generator
For #148

### LINKED ISSUE #249: Separation of Group entity and its Repository
Group and Repository should be separated. This can be useful for the following things:
* It is confusing to speak of a `Group` when you want a `Repository`. Things as inline `Comments` or `Commits` should simply not be attached to a `Group` from a ER point of view.
* Separating `Group` and `Repository` cleans up the way for having multiple repositories per course, or supporting private repositories (#252)

### LINKED ISSUE #250: Introduction of Course Editions under same course code

### LINKED ISSUE #251: GenericGenerator for compound primary keys
Implement a generic way to generate incrementing id's for compound primary keys (groups #161, pull request/issue #248)

### LINKED ISSUE #256: Switch to new Git server API
Some API changes were made in the Git server repo, in order to support the new Gitolite manager, make a clearer client API, use less code and allow for easier testing / mocking. We need to refactor the git server usage through the Devhub code base.

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
* Abstract Pull Request/Issue, impl issue number generator #248 
* GenericGenerator for compound primary keys #251 
* Separation of Group entity and its Repository #249 
* Introduction of Course Editions under same course code #250 
* Students can create same group twice #161

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
- [ ] Test migration on a backup of the deployed database
- [ ] Test persisting build results
- [ ] Full pass
- [ ] Create logic for creating course editions

**Comment by JWGmeligMeyling** [comment]
* Full pass tested under both Postgres and H2.
* Schema update tested from database backup.
* Tests should pass now as the integration tests have been updated.

**Comment by JeremybellEU** [comment]
Will you deploy this on your own testing environment so we can fiddle a bit around and verify no regressions have been created?

**Comment by JWGmeligMeyling** [comment]
Deployed on http://188.166.88.6:8080

**Comment by JWGmeligMeyling** [comment]
For live deploy we might need to reset id sequences:

```sql
CREATE OR REPLACE FUNCTION public.recheck_sequence (
)
RETURNS void AS
$body$
DECLARE
  _table_name VARCHAR;
  _column_name VARCHAR;  
  _sequence_name VARCHAR;
BEGIN
  FOR _table_name IN SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public' LOOP
    FOR _column_name IN SELECT column_name FROM information_schema.columns WHERE table_name = _table_name LOOP
        SELECT pg_get_serial_sequence(_table_name, _column_name) INTO _sequence_name;
        IF _sequence_name IS NOT NULL THEN 
            EXECUTE 'SELECT setval('''||_sequence_name||''', COALESCE((SELECT MAX('||quote_ident(_column_name)||')+1 FROM '||quote_ident(_table_name)||'), 1), FALSE);';
        END IF;
    END LOOP;   
  END LOOP;
END;
$body$
LANGUAGE 'plpgsql'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
COST 100;
```

**Pull request merged**
